app/Http/routes.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::get('images/{root}/{filename}/{width}/{height?}', function($root, $filename, $width, $height=null){
    $img = Image::make(storage_path($root."/".$filename));
    $img->resize($width, $height, function ($constraint) {
        $constraint->aspectRatio();
    });
    return $img->response();
});


Route::get('public/images/{filename}/{width}/{height}', function($filename, $width, $height){
    $img = Image::make(public_path("imgs/robes/$filename"));
    $img->resize($width, $height);
    return $img->response();
});

Route::group(['prefix' => '{locale}'], function(){
    Route::get("bride-form/create",[
        "as" => "bride-form.create",
        "uses" => "BridesController@create",
    ]);

    Route::get('mannequin-form/create',[
        "as" => "mannequin-form.create",
        "uses" => "MannequinsController@create"
    ]);

    Route::post('bride-form/data-check', [
        "as" => 'bride-form.check',
        "uses" => "BridesController@data_check"
    ]);

    Route::post('mannequin-form/data-check', [
        "as" => 'mannequin-form.check',
        "uses" => "MannequinsController@data_check"
    ]);

});

Route::post("bride-form/create",[
    "as" => "bride-form.store",
    "uses" => "BridesController@store",
]);

Route::post('mannequin-form/create',[
    "as" => "mannequin-form.store",
    "uses" => "MannequinsController@store"
]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('file/{name}', ['as' => 'file', function($name){        
        return response()->file(storage_path('cvs/'.$name));
    }]);

    Route::get('download/{name}', ['as' => 'download', function($name){
        return response()->download(storage_path('cvs/'.$name));
    }]);

    Route::resource('bride', 'BridesController',['only' => [
        'index','destroy', 'show'
    ]]);

    Route::resource('mannequin', 'MannequinsController',['only' => [
        'index','show', 'destroy'
    ]]);

    Route::controller('bride/data', 'BridesController', [
        'getBridesDatatable' => 'brides.data'
    ]);

    Route::controller('mannequin/data', 'MannequinsController', [
        'getMannequinsDatatable' => 'mannequins.data'
    ]);


    Route::get('/', [
        'as' => 'admin.index',
        'uses' => 'DashboardController@index'
    ]);

    Route::resource('robe', 'RobesController');

    Route::resource('cliente', 'ClientesController');

    Route::get('location/cliente/{cliente_id}/create', [
        'as' => 'admin.location.cliente.create',
        'uses' => 'LocationsController@createFromCliente'
    ]);

    Route::post('location/cliente/{cliente_id}/filter_list', [
        'as' => 'admin.robe.filter_list',
        'uses' => 'RobesController@filter_list'
    ]);

    Route::post('robe/filter', [
        'as' => 'admin.robe.filter',
        'uses' => 'RobesController@filter'
    ]);

    Route::post('robe/filter_list', [
        'as' => 'admin.robe.filter_list',
        'uses' => 'RobesController@filter_list'
    ]);

    Route::get('robe/update_state/{robe}', [
        'as' => 'admin.robe.update_state',
        'uses' => 'RobesController@update_state'
    ]);

    Route::get('robe/update_current_local/{robe}', [
        'as' => 'admin.robe.update_current_local',
        'uses' => 'RobesController@update_current_local'
    ]);

    Route::get('location/robe/{robe_id}/create', [
        'as' => 'admin.location.robe.create',
        'uses' => 'LocationsController@createFromRobe'
    ]);

    Route::controller('location/filter', 'LocationsController', [
        'postFilterLocation' => 'locationDatatable.filter'
    ]);

    Route::controller('cliente/data', 'ClientesController', [
        'getClientesDatatable' => 'clientes.data'
    ]);

    Route::controller('locations', 'LocationsController', [
        'getLocationDatatable'  => 'datatables.data',
        'getIndex' => 'datatables',
    ]);

    Route::get('location/datatable', [
        'as' => 'admin.location.datatable',
        'uses' => 'LocationsController@getLocations'
    ]);

    Route::resource('location', 'LocationsController');
});

Route::auth();

Route::get('/home', 'HomeController@index');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model{
    protected $fillable = [
        'cin', 'name', 'number1', 'number2', 'address'
    ];

    public function locations(){
        return $this->hasMany('App\Location');
    }
}

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Cliente;
use App\DataTables\ClientesDataTable;
use Yajra\Datatables\Datatables;

class ClientesController extends Controller{
    public function index(){
        $clientes = Cliente::latest()->get();
        return view('clientes.index', compact("clientes"));
    }

    public function getClientesDatatable(ClientesDataTable $locationDataTable){
        return $locationDataTable->render("clientes");
    }

    public function create(){
        return view('clientes.create');
    }

    public function store(Request $request){
        $cliente = new Cliente($request->input());
        $cliente->save();
        return redirect()->to(route('admin.cliente.index'));
    }

    public function filter(){

    }

    public function show($id){

    }

    public function edit($cliente){
        return view('clientes.edit', compact('cliente'));
    }

    public function update(Request $request, $cliente){
        $cliente->fill($request->input());
        $cliente->save();
        return redirect()->to(route('admin.cliente.index'));
    }

    public function destroy($cliente){
        $cliente->delete();
        return redirect()->to(route('admin.cliente.index'));
    }
}

resources/views/clientes/create.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-4 col-sm-offset-4">
        {!! Form::open(['method' => 'POST', 'route' => 'admin.cliente.store', 'class' => 'form-horizontal', 'files' => 'true']) !!}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', "Nom et prénom") !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('number1') ? ' has-error' : '' }}">
                {!! Form::label('number1', "Numéro 1") !!}
                {!! Form::text('number1', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group">
                {!! Form::label('number2', "Numéro 2") !!}
                {!! Form::text('number2', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('address', "Adresse") !!}
                {!! Form::text('address', 'Sousse', ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit("Ajouter la cliente", ['class' => 'btn btn-success']) !!}
            </div>
        {!! Form::close() !!}
    </div>
@stop

resources/views/clientes/datatable.blade.php
<table class="table table-striped" style="background:white" id="locationTable">
    <thead>
      <tr>
          <th>Nom et prénom</th>
          <th>Numéro 1</th>
          <th>Numéro 2</th>
          <th>Adresse</th>
          <th>Date de création</th>
          <th>&nbsp;</th>
      </tr>
    </thead>
</table>
@section('scripts')
    <script type="text/javascript">
        var locationTable;
        var dateColIndex = 5;
        $(document).ready(function(){
            $.extend( $.fn.dataTable.defaults, {
                autoWidth : false,
                processing: true,
                serverSide: true,
                columns: [
                    { data: 'name', name: 'name' },
                    { data: 'number1', name: 'number1' },
                    { data: 'number2', name: 'number2' },
                    { data: 'address', name: 'address' },
                    { data: 'created_at', name: 'created_at'},
                    { data: 'control', name: 'action', orderable: false, searchable: false}
                ]
            } );
        });
    </script>
    @parent
@stop

resources/views/clientes/edit.blade.php
@extends('admin.base')
@section('content')
    <div class="col-sm-4 col-sm-offset-4">
        {!! Form::model($cliente, ['route' => ['admin.cliente.update', $cliente->id], 'method' => 'PUT']) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', "Nom et prénom") !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('number1') ? ' has-error' : '' }}">
                {!! Form::label('number1', "Numéro 1") !!}
                {!! Form::text('number1', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group">
                {!! Form::label('number2', "Numéro 2") !!}
                {!! Form::text('number2', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::label('address', "Adresse") !!}
                {!! Form::text('address', null, ['class' => 'form-control']) !!}
            </div>
            <div class="form-group">
                {!! Form::submit("Modifier la cliente", ['class' => 'btn btn-success']) !!}
            </div>
        {!! Form::close() !!}
    </div>
@stop

resources/views/clientes/index.blade.php
@extends('admin.base')
@section('heading')
    <h1 class="page-header">gérer les clientes
        <small>vue général sur le boutique</small>
    </h1>
@stop
@section('content')
    <a href="{{ route('admin.cliente.create')}}" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Ajouter une cliente
    </a>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            @include('clientes.filters')
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-12">
            @include('clientes.list')
        </div>
    </div>
@stop

resources/views/clientes/list.blade.php
@include('clientes.datatable')
@section('scripts')
    @parent
    <script type="text/javascript">
        $(document).ready(function(){
            locationTable = $('#locationTable').DataTable({
                ajax: {
                    url: '{!! route('clientes.data') !!}',
                }
            });
        });
    </script>
@stop