app/Http/routes.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::get('images/{root}/{filename}/{width}/{height?}', function($root, $filename, $width, $height=null){
    $img = Image::make(storage_path($root."/".$filename));
    $img->resize($width, $height, function ($constraint) {
        $constraint->aspectRatio();
    });
    return $img->response();
});


Route::get('public/images/{filename}/{width}/{height}', function($filename, $width, $height){
    $img = Image::make(public_path("imgs/robes/$filename"));
    $img->resize($width, $height);
    return $img->response();
});

Route::group(['prefix' => '{locale}'], function(){
    Route::get("bride-form/create",[
        "as" => "bride-form.create",
        "uses" => "BridesController@create",
    ]);

    Route::get('mannequin-form/create',[
        "as" => "mannequin-form.create",
        "uses" => "MannequinsController@create"
    ]);

    Route::post('bride-form/data-check', [
        "as" => 'bride-form.check',
        "uses" => "BridesController@data_check"
    ]);

    Route::post('mannequin-form/data-check', [
        "as" => 'mannequin-form.check',
        "uses" => "MannequinsController@data_check"
    ]);

});

Route::post("bride-form/create",[
    "as" => "bride-form.store",
    "uses" => "BridesController@store",
]);

Route::post('mannequin-form/create',[
    "as" => "mannequin-form.store",
    "uses" => "MannequinsController@store"
]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {

    Route::get('file/{name}', ['as' => 'file', function($name){        
        return response()->file(storage_path('cvs/'.$name));
    }]);

    Route::get('download/{name}', ['as' => 'download', function($name){
        return response()->download(storage_path('cvs/'.$name));
    }]);

    Route::resource('bride', 'BridesController',['only' => [
        'index','destroy', 'show'
    ]]);

    Route::resource('mannequin', 'MannequinsController',['only' => [
        'index','show', 'destroy'
    ]]);

    Route::controller('bride/data', 'BridesController', [
        'getBridesDatatable' => 'brides.data'
    ]);

    Route::controller('mannequin/data', 'MannequinsController', [
        'getMannequinsDatatable' => 'mannequins.data'
    ]);


    Route::get('/', [
        'as' => 'admin.index',
        'uses' => 'DashboardController@index'
    ]);

    Route::resource('robe', 'RobesController');

    Route::resource('cliente', 'ClientesController');

    Route::get('location/cliente/{cliente_id}/create', [
        'as' => 'admin.location.cliente.create',
        'uses' => 'LocationsController@createFromCliente'
    ]);

    Route::post('location/cliente/{cliente_id}/filter_list', [
        'as' => 'admin.robe.filter_list',
        'uses' => 'RobesController@filter_list'
    ]);

    Route::post('robe/filter', [
        'as' => 'admin.robe.filter',
        'uses' => 'RobesController@filter'
    ]);

    Route::post('robe/filter_list', [
        'as' => 'admin.robe.filter_list',
        'uses' => 'RobesController@filter_list'
    ]);

    Route::get('robe/update_state/{robe}', [
        'as' => 'admin.robe.update_state',
        'uses' => 'RobesController@update_state'
    ]);

    Route::get('robe/update_current_local/{robe}', [
        'as' => 'admin.robe.update_current_local',
        'uses' => 'RobesController@update_current_local'
    ]);

    Route::get('location/robe/{robe_id}/create', [
        'as' => 'admin.location.robe.create',
        'uses' => 'LocationsController@createFromRobe'
    ]);

    Route::controller('location/filter', 'LocationsController', [
        'postFilterLocation' => 'locationDatatable.filter'
    ]);

    Route::controller('cliente/data', 'ClientesController', [
        'getClientesDatatable' => 'clientes.data'
    ]);

    Route::controller('locations', 'LocationsController', [
        'getLocationDatatable'  => 'datatables.data',
        'getIndex' => 'datatables',
    ]);

    Route::get('location/datatable', [
        'as' => 'admin.location.datatable',
        'uses' => 'LocationsController@getLocations'
    ]);

    Route::resource('location', 'LocationsController');
});

Route::auth();

Route::get('/home', 'HomeController@index');

resources/views/admin/base.blade.php
@extends('base')
@section('menu')
    @include('admin.menu')
@stop

resources/views/admin/index.blade.php
@extends('admin.base')
@section('heading')
    <h1 class="page-header">Accueil
    </h1>
@stop
@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">Prochaines locations </div>
              <div class="panel-body">
                 {{-- @include('locations.days_list') --}}
                 {{-- @include('locations.dashboard_list') --}}
              </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">Robes à réparer</div>
              <div class="panel-body">Panel Content</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">Vérifier disponibilité robe</div>
              <div class="panel-body">
                  {{-- @include('robes.categories.radio', ['categories' => App\Robe::$categories, 'name' => 'robes']) --}}
              </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
              <div class="panel-heading">Panel Heading</div>
              <div class="panel-body">Panel Content</div>
            </div>
        </div>
    </div>
@stop
@section('scripts')
@endsection

resources/views/admin/login.blade.php
@extends('public')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Login</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Adresse E-mail</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}">

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Mot de passe</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="remember"> Remember Me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-sign-in"></i> Login
                                </button>

                                <a class="btn btn-link" href="{{ url('/password/reset') }}">Forgot Your Password?</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/menu.blade.php
<nav class="navbar navbar-findcond navbar-fixed-top">
    <div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">ESPACE WAHIBA</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar">
			<ul class="nav navbar-nav navbar-right">
                <li><a href="#"><u style="color:blue">Bonjour {{ auth()->user()->name }}</u></a></li>
                @can("_", ['manage_forms'])
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Formulaires&nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ route('admin.bride.index') }}">Mariées</a></li>
                            <li><a href="{{ route('admin.mannequin.index') }}">Mannequins</a></li>
                        </ul>
                    </li>
                @endcan
                <li><a href="{{ route('admin.index') }}">Accueil</a></li>
				<li><a href="{{ route('admin.robe.index') }}">Robes</a></li>
                <li><a href="{{ route('admin.cliente.index') }}">Clientes</a></li>
                <li><a href="{{ route('admin.location.index') }}">Location</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Messages <span class="badge">0</span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Message 1</a></li>
                        <li><a href="#">Message 2</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#exit">Paramètres</a></li>
                        <li class="divider"></li>
                        <li><a href="{{ url('/logout') }}">Déconnexion</a></li>
                    </ul>
                </li>
			</ul>
			<form class="navbar-form navbar-right search-form" role="search">
				<input type="text" class="form-control" placeholder="Chercher" />
			</form>
		</div>
	</div>
</nav>